// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/strivo-hero/HeroAnimation.tsx": () => import("../components/mockups/strivo-hero/HeroAnimation.tsx")
};
