import {
  collection, getDocs, addDoc, query, where,
} from "firebase/firestore";
import { db } from "@/lib/firebase";
import type { Template } from "@/types/schema";

export const STATIC_TEMPLATES: Template[] = [
  {
    id: "t1",
    title: "Morning Workout Starter",
    category: "fitness",
    description: "A simple system to build a consistent morning exercise habit without overwhelm.",
    identityStatement: "I am someone who moves their body every single morning.",
    triggerStatement: "After I brush my teeth, I will put on my workout clothes.",
    minimumAction: "Do 5 push-ups and a 1-minute stretch.",
    rewardPlan: "Make my favourite coffee as a reward after the workout.",
    fallbackPlan: "If I miss morning, I will do just 10 squats at any point before bed.",
    isPublic: true,
  },
  {
    id: "t2",
    title: "Daily Reading Habit",
    category: "reading",
    description: "Build a consistent reading habit with a low-friction approach.",
    identityStatement: "I am a person who reads every day and keeps learning.",
    triggerStatement: "After lunch, before I check my phone, I will open my book.",
    minimumAction: "Read just one page — even if I'm tired.",
    rewardPlan: "Track my pages in an app and celebrate milestones.",
    fallbackPlan: "Listen to an audiobook version if I cannot read physically.",
    isPublic: true,
  },
  {
    id: "t3",
    title: "Deep Work Session",
    category: "deep-work",
    description: "Protect your most important focused work with a reliable trigger.",
    identityStatement: "I am someone who does focused, meaningful work every day.",
    triggerStatement: "At 9am, I put on headphones and open my top priority task.",
    minimumAction: "Work for at least 25 minutes without checking messages.",
    rewardPlan: "Take a full 5-minute break outdoors after each session.",
    fallbackPlan: "Work for even 10 minutes if energy is low. Progress beats perfection.",
    isPublic: true,
  },
  {
    id: "t4",
    title: "Evening Journaling",
    category: "mindset",
    description: "End each day with intentional reflection to process emotions and grow.",
    identityStatement: "I am a reflective person who learns from every experience.",
    triggerStatement: "After dinner, before watching anything, I open my journal.",
    minimumAction: "Write 3 sentences about what happened today.",
    rewardPlan: "Read back an old entry after writing — feel the progress.",
    fallbackPlan: "Record a 60-second voice memo instead of writing.",
    isPublic: true,
  },
  {
    id: "t5",
    title: "Meditation Practice",
    category: "meditation",
    description: "Start a sustainable meditation habit that actually sticks.",
    identityStatement: "I am someone who takes time to be still and present.",
    triggerStatement: "After I wake up and drink water, I sit in my chair and close my eyes.",
    minimumAction: "Breathe deeply for 2 minutes. Nothing else needed.",
    rewardPlan: "Track my streak and share milestones with a friend.",
    fallbackPlan: "Take 5 deep breaths in the bathroom if I'm rushed.",
    isPublic: true,
  },
  {
    id: "t6",
    title: "Content Creation Sprint",
    category: "content-creation",
    description: "Build a consistent creative output habit for makers and creators.",
    identityStatement: "I am a creator who shows up consistently, even on hard days.",
    triggerStatement: "After my morning coffee, before email, I open my draft.",
    minimumAction: "Write 100 words or record 2 minutes of content.",
    rewardPlan: "Share one finished piece per week and note the responses.",
    fallbackPlan: "Save a single idea or sentence in my notes app — ideas compound.",
    isPublic: true,
  },
  {
    id: "t7",
    title: "Sleep Wind-Down",
    category: "sleep",
    description: "Protect your sleep quality with a calming end-of-day routine.",
    identityStatement: "I am someone who protects their sleep as a form of self-care.",
    triggerStatement: "When the clock hits 10pm, I put my phone face down and dim the lights.",
    minimumAction: "Spend 10 minutes away from all screens before bed.",
    rewardPlan: "Track how rested I feel each morning and celebrate improvement.",
    fallbackPlan: "Use blue light glasses if I need to use screens late.",
    isPublic: true,
  },
  {
    id: "t8",
    title: "Relationship Check-In",
    category: "relationship",
    description: "Nurture important relationships consistently with a simple weekly habit.",
    identityStatement: "I am someone who actively maintains meaningful connections.",
    triggerStatement: "Every Sunday evening, I look at my contacts and pick one person to message.",
    minimumAction: "Send a genuine message to one person — ask how they are.",
    rewardPlan: "Schedule a catch-up call and look forward to it.",
    fallbackPlan: "Leave a voice note if texting feels too formal.",
    isPublic: true,
  },
  {
    id: "t9",
    title: "Exam Preparation",
    category: "exam-prep",
    description: "Build a reliable daily study habit that compounds into exam mastery without burnout.",
    identityStatement: "I am a focused student who prepares consistently and performs with confidence.",
    triggerStatement: "After dinner, I clear my desk, open my notes, and begin with the hardest topic first.",
    minimumAction: "Study actively for 30 minutes — no phone, no music, just deep focus.",
    rewardPlan: "After each session, mark the topic complete and reward with 10 minutes of free time.",
    fallbackPlan: "If I can't do a full session, I will spend 10 minutes reviewing flashcards — any progress counts.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t10",
    title: "Calm Evening Reset",
    category: "evening-reset",
    description: "Wind down intentionally each evening to disconnect, decompress, and set yourself up for tomorrow.",
    identityStatement: "I am someone who ends each day with intention — not just exhaustion.",
    triggerStatement: "After I eat dinner and clear the dishes, I put my phone in another room and shift to calm mode.",
    minimumAction: "Spend 10 minutes doing something that has nothing to do with work — a walk, stretching, or reading.",
    rewardPlan: "Track how rested and clear-headed I feel the next morning.",
    fallbackPlan: "If the evening is chaotic, I will do 3 slow deep breaths before bed and set tomorrow's top task.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t11",
    title: "Job Search System",
    category: "job-search",
    description: "Turn your job search from a stressful scramble into a calm, consistent daily action.",
    identityStatement: "I am someone who shows up for their career every single day, even on hard days.",
    triggerStatement: "After my morning coffee, before I open social media, I open my job search tracker.",
    minimumAction: "Send one application, make one connection request, or research one target company.",
    rewardPlan: "After each session, mark the action done and take a 10-minute walk to clear my head.",
    fallbackPlan: "If I don't have energy to apply, I will spend 10 minutes updating my resume or LinkedIn profile.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t12",
    title: "Study Sprint System",
    category: "study-sprint",
    description: "Make daily studying effortless with short, focused sprints that compound into real mastery.",
    identityStatement: "I am a learner who shows up consistently and builds knowledge one session at a time.",
    triggerStatement: "After lunch, before checking my phone, I set a 25-minute timer and open my study material.",
    minimumAction: "Complete one focused 25-minute sprint — then stop, no matter what.",
    rewardPlan: "After each sprint, take a real break: step outside, make a drink, or listen to one song.",
    fallbackPlan: "If I can only manage 10 minutes, I read one page or watch one short explanation — forward is forward.",
    isPublic: true,
    isPremium: true,
  },

  // ── New templates ────────────────────────────────────────────
  {
    id: "t13",
    title: "Daily Gratitude Practice",
    category: "gratitude",
    description: "Train your brain to scan for the good — a simple habit that measurably improves mood and resilience.",
    identityStatement: "I am someone who appreciates what they have and finds the good in each day.",
    triggerStatement: "Before I pick up my phone in the morning, I sit up and think of 3 things I'm grateful for.",
    minimumAction: "Name 3 specific things you're grateful for today — out loud or written down.",
    rewardPlan: "Once a week, read back your gratitude list and notice recurring themes.",
    fallbackPlan: "If I'm struggling, I will name just 1 tiny thing — even 'I have clean water' counts.",
    isPublic: true,
  },
  {
    id: "t14",
    title: "Morning Routine Builder",
    category: "morning-routine",
    description: "Design a powerful, consistent morning that sets the tone for your entire day.",
    identityStatement: "I am someone who starts the day with purpose and calm — not chaos.",
    triggerStatement: "The moment my alarm goes off, I do not check my phone. I drink a glass of water first.",
    minimumAction: "Complete your 3-step minimum morning: water, 2 minutes of movement, 1 intention for the day.",
    rewardPlan: "After completing my full routine, I allow myself my favourite drink — coffee, tea, or smoothie.",
    fallbackPlan: "On rushed mornings, do just the 3-step minimum. A rushed start is still a start.",
    isPublic: true,
  },
  {
    id: "t15",
    title: "Daily Hydration Habit",
    category: "hydration",
    description: "Most people are chronically dehydrated. This simple system fixes that without willpower.",
    identityStatement: "I am someone who takes care of their body by staying consistently hydrated.",
    triggerStatement: "Every time I sit down to work, I place a full water bottle on my desk first.",
    minimumAction: "Drink one full glass of water (250ml+) before each meal and before bed.",
    rewardPlan: "Track my water intake and celebrate full days with a small non-food reward.",
    fallbackPlan: "Set phone alarms for 9am, 12pm, 3pm, and 6pm as hydration reminders.",
    isPublic: true,
  },
  {
    id: "t16",
    title: "10-Minute Daily Walk",
    category: "fitness",
    description: "The most underrated health habit. A short walk daily beats sporadic intense workouts.",
    identityStatement: "I am someone who gets outside and moves their body every single day.",
    triggerStatement: "After lunch, I put on my shoes and step outside before doing anything else.",
    minimumAction: "Walk for at least 10 minutes without your phone in your hand.",
    rewardPlan: "Listen to a favourite podcast or playlist only during this walk.",
    fallbackPlan: "If I can't go outside, I walk around my home or do 5 minutes of indoor movement.",
    isPublic: true,
  },
  {
    id: "t17",
    title: "Language Learning Daily",
    category: "language",
    description: "Learn a new language consistently with a low-pressure daily system that compounds fast.",
    identityStatement: "I am someone who is actively becoming fluent — one session at a time.",
    triggerStatement: "After I brush my teeth at night, I open my language app for exactly 10 minutes.",
    minimumAction: "Complete one lesson or 10 minutes of practice — no skipping, no excuses.",
    rewardPlan: "Track my streak and reward myself with a meal from the culture I'm learning about at milestones.",
    fallbackPlan: "If I'm exhausted, watch a 5-minute YouTube video in my target language — passive input counts.",
    isPublic: true,
  },
  {
    id: "t18",
    title: "Weekly Finance Review",
    category: "finance",
    description: "Get on top of your money with a short weekly ritual. Awareness is the foundation of financial health.",
    identityStatement: "I am someone who is in control of their money and makes intentional financial decisions.",
    triggerStatement: "Every Sunday at 7pm, I open my banking app and spend 10 minutes reviewing the week.",
    minimumAction: "Review last week's spending, categorise it, and set one intention for next week.",
    rewardPlan: "Each month I hit my savings target, I treat myself to something small I've been looking forward to.",
    fallbackPlan: "If I miss Sunday, I review on Monday morning before checking emails.",
    isPublic: true,
  },
  {
    id: "t19",
    title: "Evening Strength Training",
    category: "fitness",
    description: "Build strength consistently with an after-work workout system that requires zero commute.",
    identityStatement: "I am someone who builds strength and shows up for my body after a long day.",
    triggerStatement: "When I change out of my work clothes, I immediately put on my workout clothes.",
    minimumAction: "Complete a 15-minute bodyweight routine — squats, push-ups, and a plank hold.",
    rewardPlan: "Track my reps weekly and celebrate monthly personal bests.",
    fallbackPlan: "If I'm too tired, do just 5 minutes of stretching — movement is movement.",
    isPublic: true,
  },
  {
    id: "t20",
    title: "Digital Detox Hour",
    category: "mindset",
    description: "Reclaim one hour a day from screens to reset your attention and reduce anxiety.",
    identityStatement: "I am someone who controls their relationship with technology — not the other way around.",
    triggerStatement: "At 8pm every evening, I put all devices in another room and do something offline.",
    minimumAction: "Spend 60 minutes completely offline — no checking, no glancing, no exceptions.",
    rewardPlan: "Notice how calm and clear I feel and journal one observation each week.",
    fallbackPlan: "If 60 minutes is too much, start with 20 minutes and build up each week.",
    isPublic: true,
  },
  {
    id: "t21",
    title: "Healthy Meal Prep Sunday",
    category: "nutrition",
    description: "Eliminate the 'what should I eat?' decision every day with a once-a-week prep session.",
    identityStatement: "I am someone who fuels their body with intention and plans ahead to eat well.",
    triggerStatement: "Every Sunday after breakfast, I spend 45–60 minutes preparing meals for the week.",
    minimumAction: "Prep at least 3 lunches for the coming week so healthy eating is the easy choice.",
    rewardPlan: "Try one new healthy recipe per week to keep it interesting.",
    fallbackPlan: "If I miss Sunday, I will batch-cook one simple meal on Monday evening.",
    isPublic: true,
  },
  {
    id: "t22",
    title: "Social Media Content Batching",
    category: "content-creation",
    description: "Stop the daily scramble. Batch your content once a week for a stress-free, consistent presence.",
    identityStatement: "I am a consistent creator who works smarter — not more frantically.",
    triggerStatement: "Every Tuesday morning, I block 2 hours with no interruptions and create my week's content.",
    minimumAction: "Create and schedule at least 3 pieces of content for the week ahead.",
    rewardPlan: "After each batch session, take the rest of the day completely off from creating.",
    fallbackPlan: "If I can only create 1 piece, that's the post that goes out this week — done beats perfect.",
    isPublic: true,
  },
  {
    id: "t23",
    title: "Pomodoro Deep Work",
    category: "deep-work",
    description: "Use time-boxing to protect your focus and make difficult work feel less daunting.",
    identityStatement: "I am someone who does their best work in focused, structured blocks of time.",
    triggerStatement: "At 9am, I write my one most important task, set a 25-minute timer, and start — no exceptions.",
    minimumAction: "Complete 2 Pomodoro blocks (25 min work + 5 min break) before checking anything.",
    rewardPlan: "After 4 Pomodoros, take a 30-minute guilt-free break doing whatever I like.",
    fallbackPlan: "If I can't focus, reduce to a 15-minute block. Starting always beats not starting.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t24",
    title: "Professional Networking Habit",
    category: "networking",
    description: "Build a strong professional network through small, consistent relationship-building actions.",
    identityStatement: "I am someone who invests in relationships and builds opportunities through genuine connection.",
    triggerStatement: "Every Friday at 4pm, before I finish work, I open LinkedIn and spend 15 minutes connecting.",
    minimumAction: "Send one personalised connection request or follow-up message to someone in your field.",
    rewardPlan: "Track meaningful conversations and celebrate when a connection leads to a real opportunity.",
    fallbackPlan: "If I miss Friday, I send one message on the weekend — the network doesn't care what day it is.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t25",
    title: "Morning Pages Creativity",
    category: "creativity",
    description: "Unlock creative clarity by writing 3 pages of unfiltered, uncensored thought every morning.",
    identityStatement: "I am a creative person who clears the mental clutter and accesses fresh ideas daily.",
    triggerStatement: "Before any screen time, I sit with my notebook and write continuously for 20 minutes.",
    minimumAction: "Fill at least one full page with honest, uncensored writing — no re-reading, just flowing.",
    rewardPlan: "Once a month, look back at your pages for recurring themes, fears, and breakthrough ideas.",
    fallbackPlan: "Write just one paragraph if time is short — even a tiny creative act opens the channel.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t26",
    title: "Savings Automation System",
    category: "finance",
    description: "Build real financial security by automating savings so you never need willpower.",
    identityStatement: "I am someone who pays themselves first and builds wealth through consistent action.",
    triggerStatement: "On the 1st of each month, I review my budget and confirm my automated transfers ran.",
    minimumAction: "Save at least 10% of each pay cheque — automate it so it happens before you can spend it.",
    rewardPlan: "Celebrate each savings milestone (first £500, £1000, etc.) with a small meaningful treat.",
    fallbackPlan: "If money is tight, save just £5 or $5 this month — the habit of saving matters more than the amount.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t27",
    title: "Cold Shower Challenge",
    category: "fitness",
    description: "Build mental toughness and boost energy by ending every shower with cold water.",
    identityStatement: "I am someone who does hard things daily and builds resilience through discomfort.",
    triggerStatement: "At the end of every shower, I turn the water fully cold and stay for 30 seconds.",
    minimumAction: "End your shower with at least 30 seconds of cold water — no hesitating, just do it.",
    rewardPlan: "Track my streak and notice the boost in energy and alertness over the coming weeks.",
    fallbackPlan: "If I genuinely cannot do cold, I end with slightly cooler water — still a win.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t28",
    title: "Speed Reading Practice",
    category: "reading",
    description: "Double your reading speed with a structured daily practice that retrains your eyes and brain.",
    identityStatement: "I am someone who reads efficiently and absorbs knowledge faster than most people.",
    triggerStatement: "After my morning coffee, I open my book and practice using a pointer for 15 minutes.",
    minimumAction: "Read for 15 minutes using a finger or pen as a pacer — push slightly beyond comfort speed.",
    rewardPlan: "Test your WPM once a week and track improvement — seeing growth is deeply motivating.",
    fallbackPlan: "If I'm too tired to practice technique, read normally for 10 minutes — still building the habit.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t29",
    title: "Family Connection Ritual",
    category: "relationship",
    description: "Strengthen your most important relationships with a simple, reliable weekly connection habit.",
    identityStatement: "I am someone who prioritises family and shows up for the people who matter most.",
    triggerStatement: "Every Saturday morning, before I check my phone, I call or message a family member.",
    minimumAction: "Have a genuine 10-minute conversation with one family member — no multitasking.",
    rewardPlan: "Plan one in-person gathering per month as a shared event to look forward to.",
    fallbackPlan: "If calls are hard, send a voice note or a specific, thoughtful message — presence takes many forms.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t30",
    title: "Mindful Eating Practice",
    category: "nutrition",
    description: "End mindless eating and build a healthy relationship with food through simple awareness habits.",
    identityStatement: "I am someone who eats intentionally, enjoys food fully, and listens to their body.",
    triggerStatement: "Before every meal, I take 3 deep breaths and put my phone face down on the table.",
    minimumAction: "Eat at least one meal today without any screen — phone, TV, or computer.",
    rewardPlan: "Once a week, cook a meal from scratch and eat it slowly with someone I care about.",
    fallbackPlan: "If distracted eating happens, I pause mid-meal and take 5 slow breaths to reset.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t31",
    title: "Public Speaking Confidence",
    category: "mindset",
    description: "Build unshakeable confidence speaking in front of others through regular low-stakes practice.",
    identityStatement: "I am someone who communicates clearly, confidently, and connects with any audience.",
    triggerStatement: "Every weekday during lunch, I practise speaking aloud for 5 minutes on any topic.",
    minimumAction: "Speak aloud for 5 minutes — to yourself, a mirror, or record a voice memo.",
    rewardPlan: "Join a local Toastmasters or give a talk to a small group once a month as a milestone.",
    fallbackPlan: "If I can't practice speaking, I read a chapter aloud from any book — voice practice is voice practice.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t32",
    title: "Language Immersion System",
    category: "language",
    description: "Go beyond apps and build real fluency by surrounding yourself with your target language daily.",
    identityStatement: "I am becoming fluent by making my target language a natural part of my everyday life.",
    triggerStatement: "Each morning, I change my phone language and listen to a native podcast during my commute.",
    minimumAction: "Consume at least 20 minutes of native content in your target language — podcasts, shows, or music.",
    rewardPlan: "Have one 5-minute conversation in the language each week — with a native speaker, tutor, or app.",
    fallbackPlan: "On tired days, watch a show with subtitles in the target language — passive exposure still works.",
    isPublic: true,
    isPremium: true,
  },
  {
    id: "t33",
    title: "Yoga for Flexibility",
    category: "fitness",
    description: "Improve mobility and reduce stress with a short daily yoga practice you can do anywhere.",
    identityStatement: "I am someone who takes care of their body through movement, breath, and stillness.",
    triggerStatement: "After I wake up and before breakfast, I roll out my mat and flow for 10 minutes.",
    minimumAction: "Do 5 minutes of gentle yoga stretches — even just forward folds and hip openers.",
    rewardPlan: "Once a month, try a new yoga style or attend a class as a treat.",
    fallbackPlan: "If I have no mat, I stretch in bed or on the floor — the movement matters, not the equipment.",
    isPublic: true,
  },
  {
    id: "t34",
    title: "Breathwork & Stress Relief",
    category: "meditation",
    description: "Use science-backed breathing techniques to instantly lower stress and improve focus.",
    identityStatement: "I am someone who manages stress with intention and keeps their nervous system calm.",
    triggerStatement: "Whenever I feel overwhelmed or before a stressful event, I pause and breathe deliberately.",
    minimumAction: "Do 5 rounds of box breathing: 4 counts in, 4 hold, 4 out, 4 hold.",
    rewardPlan: "Track how my stress levels change over time — improved calm is the reward.",
    fallbackPlan: "If formal breathwork isn't possible, take 3 deep slow breaths wherever I am — always accessible.",
    isPublic: true,
  },
  {
    id: "t35",
    title: "Weekly Life Admin Block",
    category: "productivity",
    description: "Stop letting small tasks pile up into a stressful backlog with a dedicated weekly admin block.",
    identityStatement: "I am someone who stays on top of life's details so I can focus on what truly matters.",
    triggerStatement: "Every Sunday at 10am, I sit down with a coffee and work through my life admin list.",
    minimumAction: "Clear at least 3 pending life tasks — emails, calls, appointments, or admin — in one session.",
    rewardPlan: "After clearing my list, enjoy the rest of Sunday completely guilt-free.",
    fallbackPlan: "If Sunday doesn't work, schedule 30 minutes mid-week — any regular slot beats no slot.",
    isPublic: true,
  },
];

/** Keep backward-compatible sync export for legacy callers */
export function getTemplates(): Template[] {
  return STATIC_TEMPLATES;
}

const col = () => collection(db, "templates");

/**
 * Fetch public templates from Firestore.
 * Falls back to static templates if the collection is empty or on error.
 */
export async function getPublicTemplates(): Promise<Template[]> {
  try {
    const q = query(col(), where("isPublic", "==", true));
    const snap = await getDocs(q);
    if (!snap.empty) {
      const templates = snap.docs.map(d => ({ id: d.id, ...d.data() } as Template));
      return templates.sort((a, b) => (a.category ?? "").localeCompare(b.category ?? ""));
    }
    await seedPublicTemplates();
    const snap2 = await getDocs(q);
    if (!snap2.empty) {
      const templates = snap2.docs.map(d => ({ id: d.id, ...d.data() } as Template));
      return templates.sort((a, b) => (a.category ?? "").localeCompare(b.category ?? ""));
    }
    return STATIC_TEMPLATES;
  } catch {
    return STATIC_TEMPLATES;
  }
}

/**
 * Seed public templates to Firestore if the collection is empty.
 * Safe to call multiple times — only seeds when no templates exist.
 */
export async function seedPublicTemplates(): Promise<void> {
  try {
    const snap = await getDocs(col());
    if (!snap.empty) return;
    await Promise.all(
      STATIC_TEMPLATES.map(({ id: _id, ...rest }) => addDoc(col(), rest)),
    );
  } catch {
    // Silently ignore — static data is the fallback
  }
}
