import type { Template } from "@/types/schema";

export function getTemplates(): Template[] {
  return [
    {
      id: "t1",
      title: "Morning Workout Starter",
      category: "fitness",
      description: "A simple system to build a consistent morning exercise habit without overwhelm.",
      identityStatement: "I am someone who moves their body every single morning.",
      triggerStatement: "After I brush my teeth, I will put on my workout clothes.",
      minimumAction: "Do 5 push-ups and a 1-minute stretch.",
      rewardPlan: "Make my favourite coffee as a reward after the workout.",
      fallbackPlan: "If I miss morning, I will do just 10 squats at any point before bed.",
      isPublic: true,
    },
    {
      id: "t2",
      title: "Daily Reading Habit",
      category: "study",
      description: "Build a consistent reading habit with a low-friction approach.",
      identityStatement: "I am a person who reads every day and keeps learning.",
      triggerStatement: "After lunch, before I check my phone, I will open my book.",
      minimumAction: "Read just one page — even if I'm tired.",
      rewardPlan: "Track my pages in an app and celebrate milestones.",
      fallbackPlan: "Listen to an audiobook version if I cannot read physically.",
      isPublic: true,
    },
    {
      id: "t3",
      title: "Deep Work Session",
      category: "career",
      description: "Protect your most important focused work with a reliable trigger.",
      identityStatement: "I am someone who does focused, meaningful work every day.",
      triggerStatement: "At 9am, I put on headphones and open my top priority task.",
      minimumAction: "Work for at least 25 minutes without checking messages.",
      rewardPlan: "Take a full 5-minute break outdoors after each session.",
      fallbackPlan: "Work for even 10 minutes if energy is low. Progress beats perfection.",
      isPublic: true,
    },
    {
      id: "t4",
      title: "Evening Journaling",
      category: "mindset",
      description: "End each day with intentional reflection to process emotions and grow.",
      identityStatement: "I am a reflective person who learns from every experience.",
      triggerStatement: "After dinner, before watching anything, I open my journal.",
      minimumAction: "Write 3 sentences about what happened today.",
      rewardPlan: "Read back an old entry after writing — feel the progress.",
      fallbackPlan: "Record a 60-second voice memo instead of writing.",
      isPublic: true,
    },
    {
      id: "t5",
      title: "Meditation Practice",
      category: "mindset",
      description: "Start a sustainable meditation habit that actually sticks.",
      identityStatement: "I am someone who takes time to be still and present.",
      triggerStatement: "After I wake up and drink water, I sit in my chair and close my eyes.",
      minimumAction: "Breathe deeply for 2 minutes. Nothing else needed.",
      rewardPlan: "Track my streak and share milestones with a friend.",
      fallbackPlan: "Take 5 deep breaths in the bathroom if I'm rushed.",
      isPublic: true,
    },
    {
      id: "t6",
      title: "Content Creation Sprint",
      category: "business",
      description: "Build a consistent creative output habit for makers and creators.",
      identityStatement: "I am a creator who shows up consistently, even on hard days.",
      triggerStatement: "After my morning coffee, before email, I open my draft.",
      minimumAction: "Write 100 words or record 2 minutes of content.",
      rewardPlan: "Share one finished piece per week and note the responses.",
      fallbackPlan: "Save a single idea or sentence in my notes app — ideas compound.",
      isPublic: true,
    },
    {
      id: "t7",
      title: "Sleep Wind-Down",
      category: "health",
      description: "Protect your sleep quality with a calming end-of-day routine.",
      identityStatement: "I am someone who protects their sleep as a form of self-care.",
      triggerStatement: "When the clock hits 10pm, I put my phone face down and dim the lights.",
      minimumAction: "Spend 10 minutes away from all screens before bed.",
      rewardPlan: "Track how rested I feel each morning and celebrate improvement.",
      fallbackPlan: "Use blue light glasses if I need to use screens late.",
      isPublic: true,
    },
    {
      id: "t8",
      title: "Relationship Check-In",
      category: "relationship",
      description: "Nurture important relationships consistently with a simple weekly habit.",
      identityStatement: "I am someone who actively maintains meaningful connections.",
      triggerStatement: "Every Sunday evening, I look at my contacts and pick one person to message.",
      minimumAction: "Send a genuine message to one person — ask how they are.",
      rewardPlan: "Schedule a catch-up call and look forward to it.",
      fallbackPlan: "Leave a voice note if texting feels too formal.",
      isPublic: true,
    },
  ];
}
